### ISSUE TITLE
We need update bower.json file after the project builded by Yoman

### ISSUE THREAD

**Issue by lanbin** [samu/angular-table#43]
add overrides into the bower.json

```javascript

  "overrides": {
    "at-table": {
      "main": "./dist/angular-table.js"
    }
  }


after add this overrides, the script tag of angular-table will not be removed while `grunt build`

**Comment by samu** [comment]
I don't understand, could you please explain a bit further?

**Comment by lanbin** [comment]
hi samu

after i install angular-table into a yoman angular project.

i add a script tag of angular-table.js in my index.html

but it would be removed after i run "grunt build"


so i add this overrides into bower.json of my project to save the tag when the project building...

it works...



my english is not good, hope u can understand what i said.

**Comment by samu** [comment]
Thanks for the details. I don't work with yoman so i haven't experienced this problem so far. Are you suggesting that i should change this projects bower.json file to include this overrides entry? Because from what i understand is, that you had to add this entry to your own bower file, which means that there isn't anything wrong with this `angular-table` and it's config. Or am i misunderstanding something?

**Comment by lanbin** [comment]
i had this problem with yoman, but there is no any issue about it.

i report this issue to provide a solution to any one who will has the same problem.

maybe we could edit the first post with solution to be more readable...

**Comment by samu** [comment]
Ok i see, thanks for reporting this! I think the description and the conversation are clear enough for somebody who runs in the same problem.
