### ISSUE TITLE
Error when data is not present

### ISSUE THREAD

**Issue by wasimakram-mulla** [samu/angular-table#61]
First Of all Angular-Table is Awesome.

Angular Table works for me the best but there is one issue i am facing.
I am getting the error "j.getList(...) is undefined" whenever there is no data in my object.
My code is working fine its just error which I am facing in my console.

I don't want any error to be printed anywhere in my angular code.

Error details:
Error: j.getList(...) is undefined
c</b.prototype.link/i@http://localhost:8080/RMS/scripts/libraries/angular-table.min.js:9:5961
c</b.prototype.link/<@http://localhost:8080/RMS/scripts/libraries/angular-table.min.js:9:6161
Zd/this.$get</k.prototype.$digest@http://localhost:8080/RMS/scripts/libraries/angular.min.js:109:422
Zd/this.$get</k.prototype.$apply@http://localhost:8080/RMS/scripts/libraries/angular.min.js:112:396
h@http://localhost:8080/RMS/scripts/libraries/angular.min.js:72:452
u@http://localhost:8080/RMS/scripts/libraries/angular.min.js:77:463
ye/</z.onreadystatechange@http://localhost:8080/RMS/scripts/libraries/angular.min.js:79:24

**Comment by samu** [comment]
@wasimakram-mulla thanks for reporting.

Please use the unminified source code of angular-table and give me the console output from there, otherwise its pretty hard to understand where the problem is caused.

**Comment by wasimakram-mulla** [comment]
@samu ,
Hi I have used the unminified version angular-table, following image show the list of issues I am facing in the application. 
Please check the same and let me know if this is possible.
Thanks in ADV.

![capture](https://cloud.githubusercontent.com/assets/6120192/9808735/a5633274-587f-11e5-885d-c900ed63bee3.PNG)

**Comment by vulpineronin** [comment]
Wondering if this was ever resolved. I am facing the same issue. I have a temporary workaround in that I specify an empty array for our table data before loading the angular-table section. I say it is temporary because we also need to pull a specific field for one of the <td> sections and, because the initial array is empty there are no fields ready for this and it continues to error.

**Comment by samu** [comment]
@wasimakram-mulla @vulpineronin sorry i completeley forgot about this.

I tried to reproduce, without success. Could please provide a jsfiddle or something like that? Thanks

**Comment by samu** [comment]
Also, what browser are you using?

**Comment by vulpineronin** [comment]
In making the Plunker I found another piece to the issue... it only occurs with pagination. If an empty table is created its fine, but if the table is paginated then the issues arise. I have a basic plunker at http://plnkr.co/edit/q7IDH3mLO7UzQCGZKzE6 to show what I was experiencing. The reason we stumbled upon it is our app will require a single page with authorization that also contains the generated table. We currently have it set to load a dummy array (see stage two note in plunker) due to other issues that arose for our specific instance. It seems though that as long as an empty object is fed to the angular table (see stage one none in plunker) that the errors will be resolved. I assume this is due to total length being calculated for the pagination. One thing that may want to be looked at though is that, even with empty data and no table being generated, the pagination bar still generates (with no visible table for it).

I think with proper variable initialization this issue can be avoided, but there would still be the issue of the pagination bar generating when the table did not (on empty data).

Note: I am using the latest Chrome for development, but testing against FF, IE (10+), Edge and Safari as well.

**Comment by samu** [comment]
@vulpineronin thanks! So i think the problem can be solved by initializing the variable that holds the data with an empty array. If the pagination needs to be hidden when no data is present, use an `ng-hide` or something similar.

I do understand the current behaviour isn't optimal, but please note i currently have no time working on this issue. I'd certainly accept a PR though :wink:
